// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth/data/user_preferences.dart';
import 'features/bible/data/scripture.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4381539499160171488),
      name: 'Scripture',
      lastPropertyId: const obx_int.IdUid(6, 3413205150055721056),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7956338616499544948),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1533607813892028835),
            name: 'book',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 8510447897508053661)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2294414593759112514),
            name: 'chapter',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7598296444351070383),
            name: 'verse',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3543460097660463035),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3413205150055721056),
            name: 'lastRead',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(2, 8525708298806220162))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4852855440985926634),
      name: 'UserPreferences',
      lastPropertyId: const obx_int.IdUid(5, 7627040479500231753),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4793686187910110002),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6923226556300231447),
            name: 'userId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 841504317878740731)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9020538119636749682),
            name: 'isStealthMode',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1496697426038210894),
            name: 'isLiteMode',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7627040479500231753),
            name: 'pinCode',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 4852855440985926634),
      lastIndexId: const obx_int.IdUid(3, 841504317878740731),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Scripture: obx_int.EntityDefinition<Scripture>(
        model: _entities[0],
        toOneRelations: (Scripture object) => [],
        toManyRelations: (Scripture object) => {},
        getId: (Scripture object) => object.id,
        setId: (Scripture object, int id) {
          object.id = id;
        },
        objectToFB: (Scripture object, fb.Builder fbb) {
          final bookOffset = fbb.writeString(object.book);
          final textOffset = fbb.writeString(object.text);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, bookOffset);
          fbb.addInt64(2, object.chapter);
          fbb.addInt64(3, object.verse);
          fbb.addOffset(4, textOffset);
          fbb.addInt64(5, object.lastRead?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastReadValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final object = Scripture()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..book = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..chapter =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..verse =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..text = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..lastRead = lastReadValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastReadValue);

          return object;
        }),
    UserPreferences: obx_int.EntityDefinition<UserPreferences>(
        model: _entities[1],
        toOneRelations: (UserPreferences object) => [],
        toManyRelations: (UserPreferences object) => {},
        getId: (UserPreferences object) => object.id,
        setId: (UserPreferences object, int id) {
          object.id = id;
        },
        objectToFB: (UserPreferences object, fb.Builder fbb) {
          final userIdOffset =
              object.userId == null ? null : fbb.writeString(object.userId!);
          final pinCodeOffset =
              object.pinCode == null ? null : fbb.writeString(object.pinCode!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addBool(2, object.isStealthMode);
          fbb.addBool(3, object.isLiteMode);
          fbb.addOffset(4, pinCodeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserPreferences()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..userId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..isStealthMode =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false)
            ..isLiteMode =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false)
            ..pinCode = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Scripture] entity fields to define ObjectBox queries.
class Scripture_ {
  /// see [Scripture.id]
  static final id =
      obx.QueryIntegerProperty<Scripture>(_entities[0].properties[0]);

  /// see [Scripture.book]
  static final book =
      obx.QueryStringProperty<Scripture>(_entities[0].properties[1]);

  /// see [Scripture.chapter]
  static final chapter =
      obx.QueryIntegerProperty<Scripture>(_entities[0].properties[2]);

  /// see [Scripture.verse]
  static final verse =
      obx.QueryIntegerProperty<Scripture>(_entities[0].properties[3]);

  /// see [Scripture.text]
  static final text =
      obx.QueryStringProperty<Scripture>(_entities[0].properties[4]);

  /// see [Scripture.lastRead]
  static final lastRead =
      obx.QueryDateProperty<Scripture>(_entities[0].properties[5]);
}

/// [UserPreferences] entity fields to define ObjectBox queries.
class UserPreferences_ {
  /// see [UserPreferences.id]
  static final id =
      obx.QueryIntegerProperty<UserPreferences>(_entities[1].properties[0]);

  /// see [UserPreferences.userId]
  static final userId =
      obx.QueryStringProperty<UserPreferences>(_entities[1].properties[1]);

  /// see [UserPreferences.isStealthMode]
  static final isStealthMode =
      obx.QueryBooleanProperty<UserPreferences>(_entities[1].properties[2]);

  /// see [UserPreferences.isLiteMode]
  static final isLiteMode =
      obx.QueryBooleanProperty<UserPreferences>(_entities[1].properties[3]);

  /// see [UserPreferences.pinCode]
  static final pinCode =
      obx.QueryStringProperty<UserPreferences>(_entities[1].properties[4]);
}
